blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://github.com/bronsonacoutts/ha-git-sync/discussions
    about: Please use Discussions for setup help, troubleshooting questions, and how-to guidance.
